package tn.esb.siad.eventAgency.Domains;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.*;

import java.time.LocalDate;

@Entity //This class is an entity (table) in the database (generated by Hibernate (ORM)
//@Getter //Lombok annotation to generate all getters
//@Setter //Lombok annotation to generate all setters
@NoArgsConstructor //Lombok's annotation to generate a constructor with no arguments
@AllArgsConstructor //Lombok's annotation to generate a constructor with all arguments
@Data
//@EqualsAndHashCode //Lombok's annotation that redefine the equals and hashcode methods
//two objects are equals if they have the same value for all their attributes
@EqualsAndHashCode (onlyExplicitlyIncluded = true)//two Events are equals if they have the same name and date
public class Event {
    @Id // this annotation tell the ORM that this attribute is the primary key of the table
    private Long id;
    @EqualsAndHashCode.Include
    private String name;
    private String description;
    private String theme;
    @EqualsAndHashCode.Include
    private LocalDate date;
    private double budget;

}
