package tn.esb.siad.eventAgency.Domains;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

@Entity //This class is an entity (table) in the database (generated by Hibernate (ORM)
//@Getter //Lombok annotation to generate all getters
//@Setter //Lombok annotation to generate all setters
@NoArgsConstructor //Lombok's annotation to generate a constructor with no arguments
//@AllArgsConstructor //Lombok's annotation to generate a constructor with all arguments
@Data
//@EqualsAndHashCode //Lombok's annotation that redefine the equals and hashcode methods
//two objects are equals if they have the same value for all their attributes
@EqualsAndHashCode (onlyExplicitlyIncluded = true)//two Events are equals if they have the same name and date
public class Event {
    @Id // this annotation tell the ORM that this attribute is the primary key of the table
    @GeneratedValue(strategy = GenerationType.IDENTITY)// the first added event will have id=1, the second id=2, ...
    private Long id;
    @EqualsAndHashCode.Include
    private String name;
    private String description;
    private String theme;
    @EqualsAndHashCode.Include
    private LocalDate date;
    private double budget;
    private int nbPlaces;
    //implement the relationship between Event and Location (*-1)
    @ManyToOne
    //referencedColumnName is optional
    @JoinColumn(name = "location_id") //this attribute is a foreign key to the location table
    private Location eventLocation;
    //implement the relationship between Event and Organizer (*-*)
    @ManyToMany
    private Set<Organizer> organizers=new HashSet<>();

}
